<?php
$movies = [
		[
				'name' => 'Hannibal',
				'year' => "2001",
				'views' => 4933,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie0.jpg',
		],
		[
				'name' => 'Battle for Sevastopol',
				'year' => "2015",
				'views' => 537,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => 'unrated',
				'href' => '#',
				'src' => 'movie1.jpg',
		],
		[
				'name' => 'Avatar',
				'year' => "2009",
				'views' => 9386,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie2.jpg',
		],
		[
				'name' => 'Avengers',
				'year' => "2012",
				'views' => 8999,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie3.jpg',
		],
		[
				'name' => 'Lord of the rings: The two towers',
				'year' => "2002",
				'views' => 8213,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie4.jpg',
		],
		[
				'name' => 'Ex Machine',
				'year' => "2015",
				'views' => 3546,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie5.jpg',
		],
		[
				'name' => 'WarCraft',
				'year' => "2016",
				'views' => 6789,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie6.jpg',
		],
		[
				'name' => 'Your Highness',
				'year' => "2011",
				'views' => 4411,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie7.jpg',
		],
		[
				'name' => 'Gladiator',
				'year' => "2000",
				'views' => 5467,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie8.jpg',
		],
		[
				'name' => 'The Prestige',
				'year' => "2006",
				'views' => 3589,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie9.jpg',
		],
		[
				'name' => 'Deadpool',
				'year' => "2016",
				'views' => 5899,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie10.jpg',
		],
		[
				'name' => 'Eagle eye',
				'year' => "2008",
				'views' => 1999,
				'comments' => rand(0, 500),
				'likes' => rand(0, 999),
				'rating' => rand(0,5),
				'href' => '#',
				'src' => 'movie11.jpg',
		],
];


echo json_encode($movies);